gate_keys = []

def wiz_storyline(ending = "wizard"):
    choice_count = 1
    choices = {
        "intro" : "You arrive at the castle, but the drawbridge has yet to be lowered for you.  A rude gesture, as a wizard of your import, who had been summoned here no less, should have been given an escort to the finest rooms of the castle.  As you sit and ponder this insulting move, sounds of steel clashing against steel begin to reach your ears.  A battle is taking place within the courtyard!  Maybe this was not so rude after all, but an inability to act.  What do you choose to do?  Cast KNOCK on the drawbridge to lower it?  Cast JUMP and leap over the wall?  Or do you LEAVE the castle to its fate?",
        "knock" : "Raising your staff high above your head, the tip thereof glowing a deep maroon, you cry the magic words aloud as you feel your spell take shape.  With a brilliant flash, the chains begin to rattle and the bridge begins its slow descent, sounds of metal blade on metal blade still ringing through the night.  As the bridge crashes to the ground before you, you can now see the knights of the castle waging a losing war against a legion of spirit warriors!  Quick, what do you do now?  Cast SLEEP and quell the fighting?  Cast FIREBALL and end the conflict, once and for all?  Or do you LEAVE the castle before those angry ghosts discover you?  ",
        "jump" : "With a quick word, you touch your staff to the ground, green energy sparking.  You feel your feet grow in power and strength, with energy running up your legs and into your torso.  With a mighty bound, you clear the moat and land on a block of stone, slightly protruding from the side of the wall.  Taking but a moment to gather your strength, you leap up into the sky, your momentum carrying you high above the battlements!  There, high in the sky, you can see the knights of the castle waging a losing war against a legion of spirit warriors!  Quick, what do you do now?  Cast LIGHTNING and cause the sky to fight for you?  Cast BANISH and attempt to quell the fighting?  Or do you let your momentum carry you back down to the ground and LEAVE?  ",
        "sleep" : "Mumbling magic mutterings of sweet nothings, you sweep your staff before you, soft lines of pale blue glowing along its length.  A glittering, sparkling dust issues forth, quickly becoming a cloud which swallows the castle whole.  As the dust settles, you can see the peacefully sleeping bodies of perhaps three-score soldiers, with twice as many spirits slowly sinking into the ground.  With the castle liberated, you turn around and head back home, satisfied in a job well done.  As you journey, you wonder if you said the words correctly.  Was it ‘with a good night’s kiss you sleep?’ or ‘until a good knight’s kiss, you sleep?’  Oh well.  Either way they might sleep a hundred years.  The Wizard Guild will not like this at all.  Oh the paperwork!",
        "fireball" : "Raising your voice to an impossible volume, the magic phrase flies out of your mouth as your staff begins to glow with a pulsating, golden light.  Pouring energy into your spell, a single mote of bright fire leaps from the tip of your staff.  It arcs through the sky into the center of the courtyard.  As the spot of light flutters through the air, soldiers and spirits alike pause to watch the progress of the tiny sun, blissfully unaware of the power of the spell you have just cast.   As the spell hits the ground in the center of all the fighting, now paused, the light ruptures and, with a sound like the earth being torn asunder, a wall of fire erupts hundreds of feet into the sky!  It expands rapidly, rushing through the courtyard and walls alike!  Jets of flame burst from arrow slits and, as the flame begins to rush across the drawbridge, you wonder if you might have overdone it.  With a wall of flame rushing towards you, you can only close your eyes and feel the blistering warmth.  Then, in a blink, the fire disappears, just inches before you.  Opening your eyes, you begin to take inventory of yourself and discover, to your immortal shame, you shall have to discover the magical secret of regrowing your own eyebrows.",
        "lightning" : "Swinging your staff in circles around your body, the air begins to swirl, creating great clouds full of magical power.  Held aloft in the air by your magical storm, you begin to direct your magic to strike the combatants below.  With deafening cracks of thunder, the sky is torn apart by brilliant flashes of yellow and blue lightning!  The deadly bolts of electricity begin to strike the attacking spirits with merciless precision.  Strike, one spirit gone.  Strike, another spirit gone.  Strike, another spir… oops.  That was a soldier.  Oh well.  With several dozen more strikes of lightning, your storm finally abates, with you landing softly on the ground in the middle of the courtyard.  The surviving soldiers are all pressed against the walls, in obvious fear and awe of your great power.  Cloak billowing behind you, you jump back over the wall, grinning from ear to ear, the rush of their admiration flowing through you.  Storm magic has always been your favorite.",
        "banish" : "Pointing your staff before you, you hurtle to the ground like a human meteor.  With a cry, and a burst of violet light, you land and expel a wave of purple energy, rushing out like a horde of rampaging bulls!  As the wave passes through the courtyard, the soldiers all stumble as the spirits they were facing suddenly disappear, banished back to the plane of death to await judgment for escaping the bonds of eternity.  As you walk through the courtyard, the soldiers begin cheering for you, some collapsing to their knees with heartfelt prayers of gratitude.  You feel a surge of pride and recognize that you have just saved the lives of these men and they will forever be in your debt.  With a casual smile, you vault back over the wall, and disappear into the night.",
        "bell" : "With a slight chuckle, understanding dawns upon you as you realize why you, specifically, were summoned.  Pulling a small, silver bell from your pocket, you tap it once against your staff.  A single, hollow chime fills the sky, the note chilling you to the bone.  All as one, the spirits cease their fighting and begin to claw at the ground and air, desperate for anything to hold on to, as their essences are vacuumed into the bell in your hand.  Laughing now, you harness the power within the bell to open a portal back to your sanctum.  Quickly moving through, you emerge back home.  You place bell in the middle of the pentagram on the floor and, with a word, release the spirits into the inscribed circle.  A few key words binds the phantoms to your service.  You flick your wrist and they all descend through the floor to a vast cavern below, filled with legions of the undead; an army built with a single purpose, the conquering of the whole world.  Beginning soft, then gradually climbing in volume, your dark laughter echoes through the halls, a sound of joy to you and a sound of impending doom to those who would dare oppose you.",
        "error" : "The Crossroads does not recognize that option.  Please try again.\n"
    }
    print(choices["intro"])
    choice = input()

    while choice_count < 3:
        if choice.lower() in choices:
            print(choices[choice.lower()])
            choice = input()
            choice_count += 1
        elif choice.lower() == "bell" and choice_count == 2:
            print(choices["bell"])
            ending = "necromancer"
            choice_count += 1
        elif choice.lower() == "leave":
            choice_count = 66
            ending = "traitor"
        else:
            choice = input(choices["error"])
    return ending

gate_keys.append(wiz_storyline())
print(gate_keys)
