window.VA = window.VA || {};
var VA = window.VA;

VA.COLLEGES = {
  civic_law: { id: 'civic_law', name: 'College of Civic Law', focus: 'Contracts, testimony, dispute resolution, magical procedure.', magicStyle: 'Loophole creation, truth pressure, precedent seals, courtroom wards.', trackA: { name: 'Pre-Law and Tribunal Practice', desc: 'You are training to argue in front of the campus tribunal - precedent, procedure, and the art of the airtight argument.' }, trackB: { name: 'Enforcement and Public Statutes', desc: 'You are training to carry the weight of the law itself - citations, wards, and the quiet authority of a badge that means something.' }, accent: '#7C8DB5', accentDark: '#2E3A59', commandWord: 'testify', accepted: ['testify', 'truth'], spell1: 'Plain Answer', spell2: 'Precedent Seal' },
  vital_sciences: { id: 'vital_sciences', name: 'College of Vital Sciences', focus: 'Medicine, anatomy, healing, research.', magicStyle: 'Pulse reading, cleansing, tissue knitting, pain suppression.', trackA: { name: 'Clinical Care and Diagnosis', desc: 'You are training to read a body like a book - symptoms, pulses, and the quiet detective work of a diagnosis.' }, trackB: { name: 'Surgical and Regenerative Arts', desc: 'You are training for the harder cases - knitting torn things back together with steady hands and steadier nerves.' }, accent: '#8FB6A8', accentDark: '#3F6659', commandWord: 'mend', accepted: ['mend', 'heal'], spell1: 'Steady Pulse', spell2: 'Cleansing Touch' },
  computational_arts: { id: 'computational_arts', name: 'College of Computational Arts', focus: 'Computers, logic systems, codes, synthetic mana.', magicStyle: 'Cipher work, pattern tracing, predictive routines, machine-soul interfacing.', trackA: { name: 'Software and Spell Systems', desc: 'You are training to write the logic that other spells run on - clean, elegant, and stubbornly reliable.' }, trackB: { name: 'Networks and Arcane Security', desc: 'You are training to guard the campus digital ley-lines - tracing intrusions and sealing the gaps.' }, accent: '#8FC1D9', accentDark: '#35507A', commandWord: 'compile', accepted: ['compile', 'run'], spell1: 'Trace Pattern', spell2: 'Cipher Trace' },
  built_worlds: { id: 'built_worlds', name: 'College of Built Worlds', focus: 'Construction, architecture, infrastructure, repair.', magicStyle: 'Reinforcement, load reading, spatial shaping, rapid assembly.', trackA: { name: 'Structural Design and Surveying', desc: 'You are training to see the bones inside a building before it is built - load, balance, and where the weak points hide.' }, trackB: { name: 'Construction Management and Materials', desc: 'You are training to get things built and keep them standing - crews, materials, and deadlines that do not bend.' }, accent: '#C9A876', accentDark: '#6B4A2F', commandWord: 'brace', accepted: ['brace', 'reinforce'], spell1: 'Steady Frame', spell2: 'Load Sense' },
  thought_ethics: { id: 'thought_ethics', name: 'College of Thought and Ethics', focus: 'Philosophy, logic, metaphysics, theory.', magicStyle: 'Concept shaping, debate pressure, paradox handling, perception testing.', trackA: { name: 'Logic and Argument', desc: 'You are training to find the crack in any argument - including, sometimes, your own.' }, trackB: { name: 'Metaphysics and Applied Theory', desc: 'You are training to work with ideas that resist being pinned down - paradox, perception, and the space between them.' }, accent: '#B7A3D6', accentDark: '#4B3B63', commandWord: 'reason', accepted: ['reason', 'question'], spell1: 'Clear Premise', spell2: 'Paradox Hold' },
  civic_commerce: { id: 'civic_commerce', name: 'College of Civic Commerce', focus: 'Economics, management, trade, logistics, negotiation.', magicStyle: 'Valuation, transport marks, resource tracking, contract favors.', trackA: { name: 'Accounting and Administration', desc: 'You are training to make the numbers tell the truth - ledgers, audits, and the discipline of a balanced book.' }, trackB: { name: 'Supply Chains and Negotiation', desc: 'You are training to move goods and people to agreement - routes, deals, and the leverage to close them.' }, accent: '#E0C374', accentDark: '#8C6D2F', commandWord: 'appraise', accepted: ['appraise', 'value'], spell1: 'True Worth', spell2: 'Fair Value' },
  arts_influence: { id: 'arts_influence', name: 'College of Arts and Influence', focus: 'Performance, media, public image, communication.', magicStyle: 'Attention shaping, emotional resonance, illusion of presence, message amplification.', trackA: { name: 'Performance and Direction', desc: 'You are training to hold a room - timing, presence, and the craft of being watched on purpose.' }, trackB: { name: 'Journalism and Public Messaging', desc: 'You are training to find a story and make sure the right people hear it, in the right order.' }, accent: '#D693B3', accentDark: '#6E2E4F', commandWord: 'resonate', accepted: ['resonate', 'project'], spell1: 'Gentle Presence', spell2: 'Borrowed Spotlight' }
};
VA.COLLEGE_ORDER = ['civic_law', 'vital_sciences', 'computational_arts', 'built_worlds', 'thought_ethics', 'civic_commerce', 'arts_influence'];
VA.NPCS = {
  alex: { id: 'alex', name: 'Alex Cartwright', role: 'an elf classmate in your own college', glyph: '&#127811;' },
  lily: { id: 'lily', name: 'Lily Arcabloom', role: 'a short, warm human from the College of Vital Sciences', glyph: '&#127807;' },
  darian: { id: 'darian', name: 'Darian Wyldman', role: 'a tall, broad-shouldered human from the College of Built Worlds', glyph: '&#127959;&#65039;' },
  clark: { id: 'clark', name: 'Clark Wayne', role: 'an orc who runs a tight, friendly ship downtown', glyph: '&#128176;' },
  britches: { id: 'britches', name: 'President Britches Elinbriin', role: 'a fairy-shaped figure who has, somehow, a degree from every college', glyph: '&#10024;' },
  moei: { id: 'moei', name: 'Dean Moei', role: 'the aaracockra dean of Civic Law', glyph: '&#129413;' },
  anacor: { id: 'anacor', name: 'Anacor Silence', role: 'a serpentian from Arts and Influence who never seems to lose', glyph: '&#128010;' },
  felix: { id: 'felix', name: 'Felix Fergerben Flip the Fifth', role: 'a nerdy Computational Arts student who always seems to need a favor', glyph: '&#128187;' }
};
VA.JOBS = {
  courier: { id: 'courier', name: 'Delivery Courier, Mercury & Co. Fast Freight', gig: 'Delivering everything from urgent takeout to forgotten textbooks, on broomstick, enchanted bicycle, or whatever is charged.', boss: 'clark', duties: ['A third-floor tenant tips you handsomely just for remembering her name.', 'A rogue weather anomaly from the meteorology wing turns your route into a light hailstorm for exactly four minutes.', 'You cut through an alley you have never noticed before and make your delivery in record time.', 'A customer argues that a bowl of dragon-pepper ramen does not count as fragile, and loses.'] },
  gremlin: { id: 'gremlin', name: 'Barista & Night-Shift Bouncer, The Gremlin\'s Mug', gig: 'Late shift at the town\'s favorite 24-hour diner and study haunt.' },
  curio: { id: 'curio', name: 'Inventory Sorter, Curio & Co. Pawnshop', gig: 'Sorting estate-sale leftovers and cast-off magical trinkets.' },
  griffin: { id: 'griffin', name: 'Assistant Groomer, The Gilded Griffin Pet Spa', gig: 'Washing griffins, detangling foxes, calming storm-spooked hellhound pups.' },
  pizzeria: { id: 'pizzeria', name: 'Line Cook, The Boiler & Basil', gig: 'Wood-fired pizza with a little elemental help.' }
};
